parent_config: ./swiftlint-base.yml

included: # paths to include during linting. Takes precedence over `excluded`.
  - Sources
  - Tests
  - Playground

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - .build
  - Docs