name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  project:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@v3
      run: swiftlint --strict --config .swiftlint-ci.yml
      working-directory: Sources

  tests:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@v3
      run: swiftlint --strict --config .swiftlint-ci.yml
      working-directory: Tests

  examples:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@v3
      run: swiftlint --strict --config .swiftlint-ci.yml
      working-directory: Examples