name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  project:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@v3
      working-directory: Sources
      with:
        args: --strict --config .swiftlint-ci.yml

  tests:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@v3
      working-directory: Tests
      with:
        args: --strict --config .swiftlint-ci.yml

  examples:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Run SwiftLint
      uses: norio-nomura/action-swiftlint@v3
      working-directory: Examples
      with:
        args: --strict --config .swiftlint-ci.yml