name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  project:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install SwiftLint
        uses: norio-nomura/action-swiftlint@v1
      - name: Run SwiftLint in Sources
        run: swiftlint --strict --config .swiftlint-ci.yml
        working-directory: Sources

  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install SwiftLint
        uses: norio-nomura/action-swiftlint@v1
      - name: Run SwiftLint in Tests
        run: swiftlint --strict --config .swiftlint-ci.yml
        working-directory: Tests

  examples:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install SwiftLint
        uses: norio-nomura/action-swiftlint@v1
      - name: Run SwiftLint in Examples
        run: swiftlint --strict --config .swiftlint-ci.yml
        working-directory: Examples
