name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dir: [Sources, Tests, Examples]
    steps:
      - uses: actions/checkout@v3

      - name: Run SwiftLint in ${{ matrix.dir }}
        uses: norio-nomura/action-swiftlint@3.2.1
        env: 
          WORKING_DIRECTORY: ${{ matrix.dir }}
