name: Linter

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: macos-latest
    strategy:
      matrix:
        dir: [Sources, Tests, Examples]
    steps:
      - uses: actions/checkout@v3

      - name: Run SwiftLint in ${{ matrix.dir }}
        uses: swift-actions/swiftlint@v1
        with:
          args: --strict --config .swiftlint-ci.yml
          working-directory: ${{ matrix.dir }}
