name: SwiftLint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  swiftlint:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Homebrew (if needed)
      run: |
        if ! which brew > /dev/null; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "HOMEBREW_PREFIX=/opt/homebrew" >> $GITHUB_ENV
          echo "HOMEBREW_ROOT=/opt/homebrew" >> $GITHUB_ENV
          echo "/opt/homebrew/bin" >> $GITHUB_PATH
        fi

    - name: Update Homebrew and Install SwiftLint
      run: |
        brew update
        brew install swiftlint

    - name: Run SwiftLint
      run: swiftlint --strict --config .swiftlint-ci.yml